version: "3.8"
services:
  db-mysql:
    image: mysql:5.6.51
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    ports:
      - 3306:3306
  samplesecurity:
    image: jakubjakubowski/samplesecurity:0.0.1-SNAPSHOT
    depends_on:
      - db-mysql
    restart: on-failure
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://172.17.0.1:3306/db
